# Python Review

Short review about some core concepts in Python exemplified by objects in the Numpy library.

Goals:

- recall basic Python vocabulary
- practice markdown syntax

## libraries and packages

**library:** is a collection of code that we can use to perform specific tasks in our programs. It can be a single file or multipile files.

**NumPy:**

- core library for numerical computing in Python
- many libraries use NumPy arrays as their building blocks
- computation on NumPy objects are optimized for speed and memory usage

Let's import NumPy with its **standard abbreviation** 'np':

In [1]:
import numpy as np

## Variables

**variable:** a name we assign to a particular object in Python

Example:

In [2]:
# Assign a small array to variable a 

a = np.array([[1,1,2],[3,5,8]])

To view a variable's value from Jupyter Notebook:

In [3]:
# Run cell with variable name to show value

a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
# can also use 'print' function to print the value
print(a)

[[1 1 2]
 [3 5 8]]


## Convention: Use 'snake_case' for naimg variables.

This is the convention we will use in the course. Why? 'my-variable' or 'MyVariable' or 'myVariable',
PEP 8 - Style Guide for Python Code recomnnends snake_case.

**Remember that variable names should be descriptive and concise!**

## Objects

**object:** (informally speaking) is a bundle of *properties* and *actions* about something specfic.

Example:

Oject: data frame
Properties: number of rows, names of column, and date created
Actions: selecting a specific row or adding a new column

A variable is the name we give a specific object, and the same object can be referenced by different variables.

In practice, we can often use the word variable and object interchangeably.

## Types

Every object in Python has a **type**, the type tells us what kind of object we have. So class and object both mean what kind of object we have.

In [5]:
print(a)

[[1 1 2]
 [3 5 8]]


In [6]:
#See the type/class of a variable/odject by using the 'type' function
type(a)

numpy.ndarray

In [8]:
print(a[0,0])
type(a[0,0])

1


numpy.int64

'numpy.int64' is not the standard Python intefet type 'int'.
numpy.int64 is a special date type in Numpy telling us that 1 is an integer stored as a 64-bit integer.

## Functions

'print' was our first example of a Python **function**

Functions take in a set of **arguments**, seperated by commas, and use those arguments to create an **output**.

In the course we'll be using argument ane paramenter interchangeably. But they do have slightly different meanings. We can ask for info about what the function does using '?'.

In [9]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


This is a **docstring** , a special type of comment that is used to document how a function (or a class, or module) works.

Notice is that there are different types of argments inside the function's parenthesis.

Roughly speaking, a function has two types of arguments:

- **non-optional arguments**: arguments *you*have to specify for the function to work.

- **optional arguments**: arguemnets that are pre-filled with a default value by the function, but you can override them. Optional arguments appear inside the parenthesis () in the form 'optional_argument = default_value,'

Example

'end' is a parameter in 'print' with default value a new line
We can pass the value ':-)' to this parameter so that it finishes the line with ":-)'.

## Attributes and methods

An object in Python has attributes and methods.

- **attributes**: a property of the object, some piece of information about it.
- **method**: a procedure associated with an object, so it is an action where the miain ingredient is the objects itself.

In [11]:
type(a.T)

numpy.ndarray

1. REad the print function help. What is the type of the argument sep? is this a default or non-default argument? Why? - default is the space

2. Create two new variable, one with the inger value 77 and another with the stirng 99.

3. Use your variable to print 77%99%77 by cahnging the value of one of the optional argumetns in 'print'

In [22]:
a = 77
b = '99'

print(a,b,a, sep='%')
print(paste0(a,b,a))

77%99%77


NameError: name 'paste0' is not defined